# Generated by Django 5.0.6 on 2024-07-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_qeustion_poletable_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polehaveoptions',
            name='user_option',
        ),
    ]
