# Generated by Django 5.0.6 on 2024-07-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_polehaveoptions_user_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='polehaveoptions',
            name='user_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poletable'),
        ),
    ]
