# Generated by Django 5.0.6 on 2024-07-07 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_polehaveoptions_user_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polehaveoptions',
            name='user_option',
        ),
    ]
