# Generated by Django 5.0.6 on 2024-07-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_polehaveoptions_user_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Poll',
        ),
    ]
