# Generated by Django 5.0.6 on 2024-07-08 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_user_poll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoleHaveOptions',
            new_name='PollHaveOptions',
        ),
        migrations.RenameModel(
            old_name='PoleTable',
            new_name='PollTable',
        ),
    ]
