# Generated by Django 5.0.6 on 2024-07-08 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_rename_polehaveoptions_pollhaveoptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollhaveoptions',
            name='user_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.polltable'),
        ),
    ]
